"""
Usage: colony ( [(--space=<space> --token=<token>)] | [--profile=<profile>] ) [--help] [--debug]
              <command> [<args>...]

Options:
  -h --help             Show this screen.
  --space=<space>       Colony Space name
  --token=<token>       Specify token generated by Colony
  --profile=<profile>   Profile indicates a section in config file.
                        If set neither --token or --space must not be specified.

Commands:
    bp, blueprint       validate colony blueprints
    sb, sandbox         start sandbox
"""
import logging
import os

from docopt import DocoptExit, docopt

from colony import commands

from .client import ColonyClient
from .config import ColonyConfigProvider, ColonyConnection
from .exceptions import ConfigError

logger = logging.getLogger(__name__)


commands_table = {
    "bp": commands.BlueprintsCommand,
    "blueprint": commands.BlueprintsCommand,
    "sb": commands.SandboxesCommand,
    "sandbox": commands.SandboxesCommand,
}


def _get_connection_params(args) -> ColonyConnection:
    # first try to get them as options or from env variable
    token = args.pop("--token", None) or os.environ.get("COLONY_TOKEN", None)
    space = args.pop("--space", None) or os.environ.get("COLONY_SPACE", None)

    # then try to load them from file
    if not all([token, space]):
        logger.debug(
            "Couldn't fetch token/space neither from command line nor environment variables"
        )
        profile = args.pop("--profile", None)
        config_file = os.environ.get("COLONY_CONFIG_PATH", None)
        try:
            colony_conn = ColonyConfigProvider(config_file).load_connection(profile)
            return colony_conn
        except ConfigError as e:
            raise DocoptExit(f"Unable to read colony credentials {e}")

    return ColonyConnection(token=token, space=space)


def main():
    args = docopt(__doc__, options_first=True)

    debug = args.pop("--debug", None)

    level = logging.DEBUG if debug else logging.WARNING
    logging.basicConfig(format="%(levelname)s - %(name)s - %(message)s", level=level)

    # Take command
    command_name = args["<command>"]
    if command_name not in commands_table:
        raise DocoptExit("Wrong command")

    # Take auth parameters
    conn = _get_connection_params(args)

    argv = [args["<command>"]] + args["<args>"]

    # Create client
    try:
        client = ColonyClient(space=conn.space, token=conn.token)
    except Exception as e:
        raise DocoptExit(f"Unable to create client. Check your token. Details {e}")

    command_class = commands_table[command_name]
    command = command_class(client, argv)
    command.execute()


if __name__ == "__main__":
    main()
