"""
Usage:
    colony [--help] [--space=<space>] [--token=<token>] <command> [<args>...]

Options:
  -h --help             Show this screen.
  --space=<space>       Colony Space name
  --token=<token>       Specify token generated by Colony

Commands:
    bp, blueprints      list, get, validate colony blueprints
"""

#TODO(ddovbii): refactor. split on modules, add subcommands
from colony import commands
from docopt import docopt, DocoptExit

from .client import ColonyClient
from pprint import pprint

commands_table = {
    'bp': commands.BlueprintsCommand,
    'blueprints': commands.BlueprintsCommand
}

def main():
    args = docopt(__doc__, options_first=True)
    client = None

    # Take command
    command_name = args['<command>']
    if command_name not in commands_table:
        raise DocoptExit("Wrong command")

    # Take auth parameters
    token = args.pop('--token', None)
    space = args.pop('--space', None)
    argv = [args['<command>']] + args['<args>']

    # Create client
    try:
        client = ColonyClient(space=space, token=token)
    except Exception as e:
        raise DocoptExit(f"Unable to create client. Check your token. Details {e}")

    command_class = commands_table[command_name]
    command = command_class(client, argv)
    command.execute()


if __name__ == '__main__':
    main()